version: '3'
services: 
  sqlserver:
    image: "mcr.microsoft.com/azure-sql-edge:latest"
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "pa55w0rd!"
      MSSQl_PID: "Express"
    ports:
      - "1433:1433"